swagger: '2.0'
info:
  title: Bank Argent API documentation
  description:  Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
  /user/profile/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: See all the transactions of the month
      description: API to retrieve a user's transactions on a monthly basis
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      meta: 
        ?sort=(amount): sort result of search about amount
        ?max-result=(20): set a max number of result (20 results)
        ?page=(2): Set a paging system (focus research on page 2)
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '401':
          description: Unauthenticated user
        '500':
          description: Internal Server Error
            /user/profile/transaction/:id:
         get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: See current transaction
      description: API to retrieve the current user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          name: _id
          description : Attach id of current product
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '401':
          description: Unauthenticated user
        '500':
          description: Internal Server Error
        /user/profile/transaction/:id:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User transaction
      description: API for post a new information on existing transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name : _id
          description: Attach id current transaction
          required: true
      produces:
        - application/json
      responses:
        '201':
          description: New information of transactions post successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User transaction
      description: Change informations on existing transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name : _id
          description: Attach id current transaction
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: update User transactions successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User transaction
      description: delete an information on existing transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          name: _id
          description : Attach id of current product
      produces:
        - application/json
      responses:
        '200':
          description: Delete User transactions successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
      
      
        