swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - "http"
paths:
  /transactions:
    get:
      tags:
        - "transactions"
      summary: "get all transactions of month"
      produces:
        - "application/xml"
        - "application/json"
      responses:
        "200":
          description: "transactions received with success"
        "401":
          description: "Bad request : unauthorized "
  /transaction/{transactionId}:
    get:
      tags:
        - "transactions"
      summary: "get all transactions of month"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "transactionId"
          in: "path"
          description: "ID of transaction to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "transaction received with success"
        "401":
          description: "Bad request : unauthorized "
    post:
      tags:
        - "transaction"
      summary: "Add information on an existing transaction"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "transactionId"
          in: "path"
          description: "ID of transaction to return"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "Transaction object that needs"
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "201":
          description: "Informations add successfully "
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Transaction not found"
        "405":
          description: "Validation exception"
    put:
      tags:
        - "transaction"
      summary: "upgrade informations on an existing transaction"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "transactionId"
          in: "path"
          description: "ID of transaction to return"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "Transaction object that needs"
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "200":
          description: "Updated information successfully"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Transaction not found"
        "405":
          description: "Validation exception"
    delete:
      tags:
        - "transaction"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "api_key"
          in: "header"
          required: false
          type: "string"
        - name: "transactionId"
          in: "path"
          description: "transaction id to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "transaction deleted"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "transaction not found"
definitions:
  Transaction:
    type: "object"
    required:
      - "catergory"
      - "note"
    properties:
      id:
        type: "integer"
        format: "int64"
      category:
        type: "string"
        example: "Food"
      note:
        type: "string"
        example: "Restaurant"
