swagger: '2.0'
info:
  title: Bank Argent API documentation
  description:  Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
  /user/profile/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: See all the transactions of the month
      description: API for fetching a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name : body
          description: period transaction
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid period
        '500':
          description: Internal Server Error
        /user/profile/transaction/:id:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User transaction
      description: API for post a new information on existing transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name : body
          description: Add information(s) on existing transaction
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: New transactions post successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User transaction
      description: Change an information on existing transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name : body
          description: Update user transaction attributes
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: update User transactions successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User transaction
      description: delete an information on existing transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name : body
          description: delete user transaction attributes
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Delete User transactions successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
      
      
        